Add hildon support to configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1932,6 +1932,9 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
         ;;
+    hildon)
+        CFG_HILDON="yes"
+        ;;
     *)
         UNKNOWN_OPT=yes
         ;;
@@ -2784,8 +2787,8 @@ fi
 
 # auto-detect support for separate debug info in objcopy
 if [ "$CFG_SEPARATE_DEBUG_INFO" != "no" ] && [ "$CFG_SHARED" = "yes" ]; then
-    TEST_COMPILER_CFLAGS=`getQMakeConf "$XQMAKESPEC" | sed -n -e 's%QMAKE_CFLAGS[^_].*=%%p' | tr '\n' ' '`
-    TEST_COMPILER_CXXFLAGS=`getQMakeConf "$XQMAKESPEC" | sed -n -e 's%QMAKE_CXXFLAGS[^_].*=%%p' | tr '\n' ' '`
+    TEST_COMPILER_CFLAGS=`getQMakeConf "$XQMAKESPEC" | sed -n -e 's%QMAKE_CFLAGS[^_][^=]*=%%p' | tr '\n' ' '`
+    TEST_COMPILER_CXXFLAGS=`getQMakeConf "$XQMAKESPEC" | sed -n -e 's%QMAKE_CXXFLAGS[^_][^=]*=%%p' | tr '\n' ' '`
     TEST_OBJCOPY=`getQMakeConf "$XQMAKESPEC" | grep "^QMAKE_OBJCOPY" | sed "s%.* *= *\(.*\)$%\1%" | tail -1`
     COMPILER_WITH_FLAGS="$TEST_COMPILER $TEST_COMPILER_CXXFLAGS"
     COMPILER_WITH_FLAGS=`echo "$COMPILER_WITH_FLAGS" | sed -e "s%\\$\\$QMAKE_CFLAGS%$TEST_COMPILER_CFLAGS%g"`
@@ -3073,8 +3076,8 @@ Usage:  $relconf [-h] [-prefix <dir>] [-prefix-install] [-bindir <dir>] [-libdir
         [-no-separate-debug-info] [-no-mmx] [-no-3dnow] [-no-sse] [-no-sse2]
         [-qtnamespace <namespace>] [-qtlibinfix <infix>] [-separate-debug-info] [-armfpa]
         [-no-optimized-qmake] [-optimized-qmake] [-no-xmlpatterns] [-xmlpatterns]
-        [-no-phonon] [-phonon] [-no-phonon-backend] [-phonon-backend]
-        [-no-openssl] [-openssl] [-openssl-linked]
+        [-no-phonon] [-phonon] [-no-phonon-backend] [-phonon-backend] [-hildon]
+	[-no-openssl] [-openssl] [-openssl-linked]
         [-no-gtkstyle] [-gtkstyle] [-no-svg] [-svg] [-no-webkit] [-webkit]
         [-no-scripttools] [-scripttools]
 
@@ -5071,6 +5074,27 @@ if [ "$PLATFORM_X11" = "yes" ]; then
     elif [ "$CFG_GLIB" = "no" ]; then
         CFG_QGTKSTYLE=no
     fi
+
+    if [ "$CFG_HILDON" == "yes" -a "$CFG_QGTKSTYLE" = "yes" ]; then
+        if [ -n "$PKG_CONFIG" ]; then
+            QT_CFLAGS_HILDON=`$PKG_CONFIG --cflags hildon-1 2>/dev/null`
+            #QT_LIBS_HILDON=`$PKG_CONFIG --libs gtk+-x11-2.0 hildon-1 2>/dev/null`
+            QMakeVar set QT_CFLAGS_HILDON "$QT_CFLAGS_HILDON"
+            #QMakeVar set QT_LIBS_HILDON "$QT_LIBS_HILDON"
+            #QMakeVar set styles "plastique gtk windows" #NO motif
+            # Add Hildon to config.h
+            QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_XIM Q_WS_HILDON QT_NO_SIZEGRIP"
+        else
+            echo "Hildon support cannot be enabled due to functionality test!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        fi
+    else
+        CFG_HILDON="no"
+    fi
+
 fi # X11
 
 
@@ -6594,6 +6618,9 @@ else
     QT_CONFIG="$QT_CONFIG qt_framework"
     QTCONFIG_CONFIG="$QTCONFIG_CONFIG qt_framework"
 fi
+if [ "$CFG_HILDON" == "yes" -a "$CFG_QGTKSTYLE" = "yes" ]; then
+	    QT_CONFIG="$QT_CONFIG hildon"
+fi
 if [ "$PLATFORM_MAC" = "yes" ]; then
     QT_CONFIG="$QT_CONFIG $CFG_MAC_ARCHS"
 fi
@@ -6949,6 +6976,7 @@ if [ "$PLATFORM_X11" = "yes" ]; then
     echo "XKB Support ......... $CFG_XKB"
     echo "immodule support .... $CFG_IM"
     echo "GTK theme support ... $CFG_QGTKSTYLE"
+    echo "Hildon support  ..... $CFG_HILDON"
 fi
 [ "$CFG_SQL_mysql" != "no" ] && echo "MySQL support ....... $CFG_SQL_mysql"
 [ "$CFG_SQL_psql" != "no" ] && echo "PostgreSQL support .. $CFG_SQL_psql"
